version: 1.0.{build}
install:
- cmd: cinst scriptcs
build_script:
- cmd: >-
    cd build

    scriptcs build.csx -debug
test: off
artifacts:
- path: build/tmp/*.nupkg
  name: NuGet Packages
deploy:
  provider: NuGet  
  api_key:
    secure: ynFcRQX0oim3DdR5Y8s4BtynS/NYRG059GvWGckqhpZGNZVvhvvn5UUWgsyPKLKm
  skip_symbols: false  
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
